work_dir: /data/wangkun/project/work_dir/EnsCLR/pkummd_240121
#weights: /data/wangkun/project/work_dir/EnsCLR/pkummd/epoch145_model.pt
# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: /data/wangkun/project/datasets/pku_part1_frame50/xsub/train_position.npy
  label_path: /data/wangkun/project/datasets/pku_part1_frame50/xsub/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.ensemble_aimclr.CLR
model_args:
  base_encoder: net.st_gcn.STGCNModel
  pretrain: True
  feature_dim: 128
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.07
  mlp: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 51
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [250]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 300
start_epoch: 0

topk: 1
view: 'all'
mining_epoch: 150
context: True
cross: False
ensemble: True

# log
save_interval: 5
eval_interval: -1
